name: 'YAML File Reader'
author: 'Ankur Mangal'
description: 'Script that reads values from a YAML file and sets them as GitHub Environment variables and GitHub outputs'
branding:
  icon: code
  color: purple
inputs:
  yaml-file:
    description: 'Absolute path of the YAML file with filename'
    required: true

  keys:
    description: key name to be set in case of multiple use ","
    required: false
    default: 'all'

  key-transformation:
    description: 'Option to apply key formatting: uppercase, lowercase, or none'
    required: false
    default: 'none'
    
  set-env-vars:
    description: 'Assign key-value pairs to GitHub environment variables'
    required: false
    default: true

outputs:
  data:
    description: 'Key values data Read form YAML file'
    value: ${{ toJson(steps.read_yaml_file.outputs) }}

runs:
  using: "composite"
  steps:
    - id: read_yaml_file
      run: |
        chmod +x ./code-files/script.sh
        data=$(./code-files/script.sh  ${{ inputs.yaml-file }} ${{ inputs.key-transformation }} ${{ inputs.set-env-vars }} ${{ inputs.keys }})
        for var in $data; do
          echo "$var" >> $GITHUB_OUTPUT
        done
      shell: bash